#!/bin/bash


# Compile indraniel/fqgrep
make


# Create alias for Indraniel Das' fqgrep("~/.local/bin" is in the PATH)
#mkdir -p ~/.local/bin
#cd ~/.local/bin
#mv ~/fqgrep .
#ln -s ~/.local/bin/fqgrep fqgrep