#!/bin/bash

# clean up / declutter a bit ;
# this will make it easier to see the files produced
rm Makefile
rm README
rm bm.c
rm bm.h
rm fqgrep.c
rm kseq.h
rm tre-test.c


# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"